### ISSUE TITLE
"This item cannot be installed in your devices country"

### ISSUE THREAD

**Issue by padraic7a** [thoughtbot/tropos-android#11]
Hi,

I just tried to install this in Ireland but was rejected b the Play store. 

Is this an oversight?

**Comment by mandybess** [comment]
Unfortunately, no. For now it’s only available in the US - but that’s entirely because we didn’t localize temperatures so they only show in Fahrenheit. I have a branch adding a settings screen so people can specify their preference once that gets merged well add the rest of the metric world 👍

**Comment by padraic7a** [comment]
That makes sense. Looking forward to trying it.

**Comment by mandybess** [comment]
This is solved in #15 and is now released as of [Version 1.1](https://github.com/thoughtbot/tropos-android/blob/master/CHANGELOG.md#version-11---february-14th-2017)
