### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by alexfu** [thoughtbot/tropos-android#13]
Adding a `CHANGELOG` would be very beneficial to existing and new contributors since it would give us a quick overview of the state of the project. Plus, it's nice to know what's changed between versions without looking through PRs.

I realize not everyone likes to write `CHANGELOG`s which is why I recommend [github-changelog-generator](https://github.com/skywinder/github-changelog-generator). It will generate a `CHANGELOG` from PRs and issues on Github.

**Comment by mandybess** [comment]
Added [here](https://github.com/thoughtbot/tropos-android/commit/efc88d1aea4993f0ccd5bf7138448c48eafc2c03)
